/**
 * Plotter Export - Total Serialism
 * Export paths to G-code, HPGL, and preview visualization
 */

// ============================================
// G-Code Exporter
// ============================================
class GCodeExporter {
  constructor(config = {}) {
    this.config = {
      plotterType: 'generic',
      drawSpeed: 1500,
      moveSpeed: 3000,
      penUpHeight: 5,
      penDownHeight: 0,
      width: 210,
      height: 297,
      ...config
    };
  }

  export(paths) {
    let gcode = this.getHeader();

    paths.forEach((path, index) => {
      if (!path.points || path.points.length < 2) return;

      // Move to start position (pen up)
      gcode += this.penUp();
      gcode += this.moveTo(path.points[0].x, path.points[0].y, this.config.moveSpeed);

      // Lower pen and draw
      gcode += this.penDown();

      for (let i = 1; i < path.points.length; i++) {
        gcode += this.lineTo(path.points[i].x, path.points[i].y, this.config.drawSpeed);
      }
    });

    gcode += this.penUp();
    gcode += this.getFooter();

    return gcode;
  }

  getHeader() {
    switch (this.config.plotterType) {
      case 'axidraw':
        return '; AxiDraw G-code\n; Generated by Total Serialism\nG21 ; mm mode\nG90 ; absolute positioning\n\n';
      case 'grbl':
        return '; GRBL G-code\n; Generated by Total Serialism\nG21 ; mm mode\nG90 ; absolute positioning\nG0 Z5 ; raise pen\nG0 X0 Y0 ; home\n\n';
      default:
        return '; G-code for Pen Plotter\n; Generated by Total Serialism\nG21 ; mm mode\nG90 ; absolute positioning\n\n';
    }
  }

  getFooter() {
    return '\nG0 X0 Y0 ; return home\nM30 ; program end\n';
  }

  penUp() {
    return `G0 Z${this.config.penUpHeight} ; pen up\n`;
  }

  penDown() {
    return `G0 Z${this.config.penDownHeight} ; pen down\n`;
  }

  moveTo(x, y, speed) {
    return `G0 X${x.toFixed(3)} Y${y.toFixed(3)} F${speed}\n`;
  }

  lineTo(x, y, speed) {
    return `G1 X${x.toFixed(3)} Y${y.toFixed(3)} F${speed}\n`;
  }

  estimateTime(paths) {
    let drawDistance = 0;
    let travelDistance = 0;
    let penLifts = 0;
    let currentPos = { x: 0, y: 0 };

    paths.forEach(path => {
      if (!path.points || path.points.length < 2) return;

      // Travel to start
      travelDistance += this.distance(currentPos, path.points[0]);
      penLifts++;

      // Drawing
      for (let i = 1; i < path.points.length; i++) {
        drawDistance += this.distance(path.points[i - 1], path.points[i]);
      }

      currentPos = path.points[path.points.length - 1];
    });

    const drawTime = drawDistance / (this.config.drawSpeed / 60); // mm/s
    const moveTime = travelDistance / (this.config.moveSpeed / 60);
    const liftTime = penLifts * 0.3; // seconds per lift

    return {
      pathCount: paths.length,
      totalDistance: drawDistance + travelDistance,
      drawDistance,
      travelDistance,
      drawTime,
      moveTime,
      totalTime: drawTime + moveTime + liftTime
    };
  }

  distance(p1, p2) {
    const dx = p2.x - p1.x;
    const dy = p2.y - p1.y;
    return Math.sqrt(dx * dx + dy * dy);
  }
}

// ============================================
// HPGL Exporter
// ============================================
class HPGLExporter {
  constructor(config = {}) {
    this.config = {
      paperWidth: 8.5,
      paperHeight: 11,
      penNumber: 1,
      penSpeed: 50,
      unitsPerInch: 1016, // HPGL units per inch
      ...config
    };
  }

  export(paths) {
    let hpgl = this.getHeader();

    paths.forEach(path => {
      if (!path.points || path.points.length < 2) return;

      // Pen up, move to start
      hpgl += 'PU;';
      hpgl += this.moveTo(path.points[0]);

      // Pen down, draw path
      hpgl += 'PD;';
      for (let i = 1; i < path.points.length; i++) {
        hpgl += this.moveTo(path.points[i]);
      }
    });

    hpgl += this.getFooter();
    return hpgl;
  }

  getHeader() {
    return `IN;SP${this.config.penNumber};VS${this.config.penSpeed};`;
  }

  getFooter() {
    return 'PU;SP0;IN;';
  }

  moveTo(point) {
    const x = Math.round(point.x * this.config.unitsPerInch / 25.4); // mm to HPGL units
    const y = Math.round(point.y * this.config.unitsPerInch / 25.4);
    return `PA${x},${y};`;
  }

  /**
   * Sample a browser-native SVG path when geometry APIs are available.
   */
  samplePathData(d, segmentLength = 4) {
    if (typeof document === 'undefined' || !document.createElementNS) {
      return null;
    }

    try {
      const ns = 'http://www.w3.org/2000/svg';
      const svg = document.createElementNS(ns, 'svg');
      const path = document.createElementNS(ns, 'path');
      path.setAttribute('d', d);
      svg.appendChild(path);
      svg.setAttribute('width', '0');
      svg.setAttribute('height', '0');
      svg.style.position = 'absolute';
      svg.style.opacity = '0';
      svg.style.pointerEvents = 'none';
      document.body.appendChild(svg);

      const totalLength = path.getTotalLength();
      const samples = Math.max(8, Math.ceil(totalLength / segmentLength));
      const points = [];

      for (let i = 0; i <= samples; i++) {
        const point = path.getPointAtLength((totalLength * i) / samples);
        points.push({ x: point.x, y: point.y });
      }

      document.body.removeChild(svg);
      return points;
    } catch (error) {
      return null;
    }
  }

  createPolylinePath(points, closed = false) {
    return {
      points: points.filter((point) => Number.isFinite(point.x) && Number.isFinite(point.y)),
      closed
    };
  }

  approximateEllipse(cx, cy, rx, ry, segments = 72) {
    const points = [];
    for (let i = 0; i <= segments; i++) {
      const angle = (i / segments) * Math.PI * 2;
      points.push({
        x: cx + rx * Math.cos(angle),
        y: cy + ry * Math.sin(angle)
      });
    }
    return this.createPolylinePath(points, true);
  }

  /**
   * Parse SVG path data into point arrays.
   */
  parseSVGPath(d) {
    const sampled = this.samplePathData(d);
    if (sampled && sampled.length > 1) {
      return [this.createPolylinePath(sampled, /[Zz]\s*$/.test(d.trim()))];
    }

    const paths = [];
    const commands = d.match(/[MmLlHhVvZz][^MmLlHhVvZz]*/g);
    if (!commands) return paths;

    let currentPath = { points: [], closed: false };
    let currentX = 0;
    let currentY = 0;
    let startX = 0;
    let startY = 0;

    commands.forEach((cmd) => {
      const type = cmd[0];
      const coords = cmd.slice(1).trim().split(/[\s,]+/).filter(Boolean).map(parseFloat);

      switch (type) {
        case 'M':
        case 'm':
          if (currentPath.points.length > 0) {
            paths.push(currentPath);
            currentPath = { points: [], closed: false };
          }
          currentX = type === 'M' ? coords[0] : currentX + coords[0];
          currentY = type === 'M' ? coords[1] : currentY + coords[1];
          startX = currentX;
          startY = currentY;
          currentPath.points.push({ x: currentX, y: currentY });
          break;
        case 'L':
        case 'l':
          for (let i = 0; i < coords.length; i += 2) {
            currentX = type === 'L' ? coords[i] : currentX + coords[i];
            currentY = type === 'L' ? coords[i + 1] : currentY + coords[i + 1];
            currentPath.points.push({ x: currentX, y: currentY });
          }
          break;
        case 'H':
        case 'h':
          currentX = type === 'H' ? coords[0] : currentX + coords[0];
          currentPath.points.push({ x: currentX, y: currentY });
          break;
        case 'V':
        case 'v':
          currentY = type === 'V' ? coords[0] : currentY + coords[0];
          currentPath.points.push({ x: currentX, y: currentY });
          break;
        case 'Z':
        case 'z':
          currentPath.points.push({ x: startX, y: startY });
          currentPath.closed = true;
          currentX = startX;
          currentY = startY;
          break;
      }
    });

    if (currentPath.points.length > 0) {
      paths.push(currentPath);
    }

    return paths;
  }

  /**
   * Parse a full SVG document into plotter-ready path objects.
   */
  parseSVGContent(svgString) {
    const parser = new DOMParser();
    const doc = parser.parseFromString(svgString, 'image/svg+xml');
    const svg = doc.documentElement;

    if (!svg || svg.tagName.toLowerCase() !== 'svg') {
      return [];
    }

    const paths = [];
    svg.querySelectorAll('path, line, polyline, polygon, rect, circle, ellipse').forEach((element) => {
      const tag = element.tagName.toLowerCase();

      if (tag === 'path') {
        const d = element.getAttribute('d');
        if (d) {
          paths.push(...this.parseSVGPath(d));
        }
        return;
      }

      if (tag === 'line') {
        paths.push(this.createPolylinePath([
          { x: parseFloat(element.getAttribute('x1') || 0), y: parseFloat(element.getAttribute('y1') || 0) },
          { x: parseFloat(element.getAttribute('x2') || 0), y: parseFloat(element.getAttribute('y2') || 0) }
        ]));
        return;
      }

      if (tag === 'polyline' || tag === 'polygon') {
        const points = (element.getAttribute('points') || '')
          .trim()
          .split(/\s+/)
          .filter(Boolean)
          .map((pair) => {
            const [x, y] = pair.split(',').map(Number);
            return { x, y };
          });
        paths.push(this.createPolylinePath(points, tag === 'polygon'));
        return;
      }

      if (tag === 'rect') {
        const x = parseFloat(element.getAttribute('x') || 0);
        const y = parseFloat(element.getAttribute('y') || 0);
        const width = parseFloat(element.getAttribute('width') || 0);
        const height = parseFloat(element.getAttribute('height') || 0);
        paths.push(this.createPolylinePath([
          { x, y },
          { x: x + width, y },
          { x: x + width, y: y + height },
          { x, y: y + height },
          { x, y }
        ], true));
        return;
      }

      if (tag === 'circle') {
        const cx = parseFloat(element.getAttribute('cx') || 0);
        const cy = parseFloat(element.getAttribute('cy') || 0);
        const r = parseFloat(element.getAttribute('r') || 0);
        paths.push(this.approximateEllipse(cx, cy, r, r));
        return;
      }

      if (tag === 'ellipse') {
        const cx = parseFloat(element.getAttribute('cx') || 0);
        const cy = parseFloat(element.getAttribute('cy') || 0);
        const rx = parseFloat(element.getAttribute('rx') || 0);
        const ry = parseFloat(element.getAttribute('ry') || 0);
        paths.push(this.approximateEllipse(cx, cy, rx, ry));
      }
    });

    return paths.filter((path) => path.points && path.points.length > 1);
  }
}

// ============================================
// Plot Preview
// ============================================
class PlotPreview {
  constructor(canvas, options = {}) {
    this.canvas = canvas;
    this.ctx = canvas.getContext('2d');
    this.options = {
      showStats: true,
      pathColor: '#000000',
      travelColor: 'rgba(255, 0, 0, 0.3)',
      backgroundColor: '#ffffff',
      ...options
    };

    this.paths = [];
    this.animationState = {
      playing: false,
      currentPath: 0,
      currentPoint: 0,
      speed: 10
    };

    this.onProgress = null;
    this.onComplete = null;
  }

  loadPaths(paths) {
    this.paths = paths;
    this.animationState.currentPath = 0;
    this.animationState.currentPoint = 0;
    this.render();
  }

  render() {
    const ctx = this.ctx;
    const width = this.canvas.width;
    const height = this.canvas.height;

    // Clear
    ctx.fillStyle = this.options.backgroundColor;
    ctx.fillRect(0, 0, width, height);

    // Scale paths to fit canvas
    const bounds = this.getBounds(this.paths);
    const scale = Math.min(
      (width - 40) / (bounds.maxX - bounds.minX || 1),
      (height - 40) / (bounds.maxY - bounds.minY || 1)
    );
    const offsetX = 20 - bounds.minX * scale;
    const offsetY = 20 - bounds.minY * scale;

    // Draw paths
    ctx.strokeStyle = this.options.pathColor;
    ctx.lineWidth = 2;

    this.paths.forEach(path => {
      if (!path.points || path.points.length < 2) return;

      ctx.beginPath();
      ctx.moveTo(
        path.points[0].x * scale + offsetX,
        path.points[0].y * scale + offsetY
      );

      for (let i = 1; i < path.points.length; i++) {
        ctx.lineTo(
          path.points[i].x * scale + offsetX,
          path.points[i].y * scale + offsetY
        );
      }

      ctx.stroke();
    });
  }

  getBounds(paths) {
    let minX = Infinity, minY = Infinity;
    let maxX = -Infinity, maxY = -Infinity;

    paths.forEach(path => {
      if (!path.points) return;
      path.points.forEach(p => {
        minX = Math.min(minX, p.x);
        minY = Math.min(minY, p.y);
        maxX = Math.max(maxX, p.x);
        maxY = Math.max(maxY, p.y);
      });
    });

    return { minX, minY, maxX, maxY };
  }

  play() {
    if (this.paths.length === 0) return;

    this.animationState.playing = true;
    this.animate();
  }

  pause() {
    this.animationState.playing = false;
  }

  stop() {
    this.animationState.playing = false;
    this.animationState.currentPath = 0;
    this.animationState.currentPoint = 0;
    this.render();
  }

  setSpeed(speed) {
    this.animationState.speed = speed;
  }

  animate() {
    if (!this.animationState.playing) return;

    const ctx = this.ctx;
    const width = this.canvas.width;
    const height = this.canvas.height;

    // Calculate bounds and scale
    const bounds = this.getBounds(this.paths);
    const scale = Math.min(
      (width - 40) / (bounds.maxX - bounds.minX || 1),
      (height - 40) / (bounds.maxY - bounds.minY || 1)
    );
    const offsetX = 20 - bounds.minX * scale;
    const offsetY = 20 - bounds.minY * scale;

    // Clear
    ctx.fillStyle = this.options.backgroundColor;
    ctx.fillRect(0, 0, width, height);

    // Draw completed paths
    ctx.strokeStyle = this.options.pathColor;
    ctx.lineWidth = 2;

    for (let i = 0; i < this.animationState.currentPath; i++) {
      const path = this.paths[i];
      if (!path.points || path.points.length < 2) continue;

      ctx.beginPath();
      ctx.moveTo(
        path.points[0].x * scale + offsetX,
        path.points[0].y * scale + offsetY
      );

      for (let j = 1; j < path.points.length; j++) {
        ctx.lineTo(
          path.points[j].x * scale + offsetX,
          path.points[j].y * scale + offsetY
        );
      }
      ctx.stroke();
    }

    // Draw current path progress
    if (this.animationState.currentPath < this.paths.length) {
      const currentPath = this.paths[this.animationState.currentPath];
      if (currentPath.points && currentPath.points.length >= 2) {
        ctx.beginPath();
        ctx.moveTo(
          currentPath.points[0].x * scale + offsetX,
          currentPath.points[0].y * scale + offsetY
        );

        for (let j = 1; j <= this.animationState.currentPoint && j < currentPath.points.length; j++) {
          ctx.lineTo(
            currentPath.points[j].x * scale + offsetX,
            currentPath.points[j].y * scale + offsetY
          );
        }
        ctx.stroke();

        // Draw pen position
        if (this.animationState.currentPoint < currentPath.points.length) {
          const penPos = currentPath.points[this.animationState.currentPoint];
          ctx.fillStyle = '#ff0000';
          ctx.beginPath();
          ctx.arc(
            penPos.x * scale + offsetX,
            penPos.y * scale + offsetY,
            4, 0, Math.PI * 2
          );
          ctx.fill();
        }
      }
    }

    // Calculate progress
    let totalPoints = 0;
    let completedPoints = 0;
    this.paths.forEach((path, i) => {
      if (!path.points) return;
      totalPoints += path.points.length;
      if (i < this.animationState.currentPath) {
        completedPoints += path.points.length;
      } else if (i === this.animationState.currentPath) {
        completedPoints += this.animationState.currentPoint;
      }
    });

    const progress = totalPoints > 0 ? completedPoints / totalPoints : 0;

    if (this.onProgress) {
      this.onProgress(progress, { currentPath: this.animationState.currentPath });
    }

    // Advance animation
    this.animationState.currentPoint += this.animationState.speed;

    if (this.animationState.currentPath < this.paths.length) {
      const currentPathPoints = this.paths[this.animationState.currentPath].points?.length || 0;
      if (this.animationState.currentPoint >= currentPathPoints) {
        this.animationState.currentPath++;
        this.animationState.currentPoint = 0;
      }
    }

    // Continue or complete
    if (this.animationState.currentPath < this.paths.length) {
      requestAnimationFrame(() => this.animate());
    } else {
      this.animationState.playing = false;
      if (this.onComplete) {
        this.onComplete();
      }
    }
  }
}

// Export
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { GCodeExporter, HPGLExporter, PlotPreview };
}
